/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project.pkg1;

/**
 *
 * @author SK_KUTTY_CRUSH
 */
public class javaproject2 extends javax.swing.JFrame {

    /**
     * Creates new form javaproject2
     */
    public javaproject2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        subbutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        muxbutton = new javax.swing.JButton();
        divbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        enter1 = new javax.swing.JButton();
        xbut = new javax.swing.JButton();
        agebutton = new javax.swing.JButton();
        primebutton = new javax.swing.JButton();
        OEbutton = new javax.swing.JButton();
        BANKBUTTON4 = new javax.swing.JButton();
        palindromebutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        subbutton.setBackground(new java.awt.Color(255, 0, 51));
        subbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subbutton.setForeground(new java.awt.Color(255, 255, 255));
        subbutton.setText("SUBTRACTION");
        subbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbuttonActionPerformed(evt);
            }
        });

        addbutton.setBackground(new java.awt.Color(255, 0, 51));
        addbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("ADDITION");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        muxbutton.setBackground(new java.awt.Color(255, 0, 51));
        muxbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        muxbutton.setForeground(new java.awt.Color(255, 255, 255));
        muxbutton.setText("MULTIPLICATION");
        muxbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muxbuttonActionPerformed(evt);
            }
        });

        divbutton.setBackground(new java.awt.Color(255, 0, 51));
        divbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        divbutton.setForeground(new java.awt.Color(255, 255, 255));
        divbutton.setText("DIVISION");
        divbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("search");

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        enter1.setForeground(new java.awt.Color(255, 0, 0));
        enter1.setText("ENTER");
        enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter1ActionPerformed(evt);
            }
        });

        xbut.setText("X");
        xbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbutActionPerformed(evt);
            }
        });

        agebutton.setBackground(new java.awt.Color(255, 0, 51));
        agebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agebutton.setForeground(new java.awt.Color(255, 255, 255));
        agebutton.setText("AGE CALCI");
        agebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agebuttonActionPerformed(evt);
            }
        });

        primebutton.setBackground(new java.awt.Color(255, 0, 51));
        primebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        primebutton.setForeground(new java.awt.Color(255, 255, 255));
        primebutton.setText("PRIMENUMBER");
        primebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primebuttonActionPerformed(evt);
            }
        });

        OEbutton.setBackground(new java.awt.Color(255, 0, 51));
        OEbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OEbutton.setForeground(new java.awt.Color(255, 255, 255));
        OEbutton.setText("ODD (OR) EVEN");
        OEbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OEbuttonActionPerformed(evt);
            }
        });

        BANKBUTTON4.setBackground(new java.awt.Color(255, 0, 51));
        BANKBUTTON4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BANKBUTTON4.setForeground(new java.awt.Color(255, 255, 255));
        BANKBUTTON4.setText("FACTORIAL");
        BANKBUTTON4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BANKBUTTON4ActionPerformed(evt);
            }
        });

        palindromebutton.setBackground(new java.awt.Color(255, 0, 51));
        palindromebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        palindromebutton.setForeground(new java.awt.Color(255, 255, 255));
        palindromebutton.setText("PALINDROME");
        palindromebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palindromebuttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JAVA CODES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enter1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muxbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(palindromebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(primebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(OEbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BANKBUTTON4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(subbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xbut)
                    .addComponent(enter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muxbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OEbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BANKBUTTON4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(palindromebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        addition add=new addition();
        add.show();
        dispose();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void subbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbuttonActionPerformed
        // TODO add your handling code here:
        subraction sub=new subraction();
        sub.show();
        dispose();
        
    }//GEN-LAST:event_subbuttonActionPerformed

    private void muxbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muxbuttonActionPerformed
        // TODO add your handling code here:
        multiplication mux=new multiplication();
        mux.show();
        dispose();
        
    }//GEN-LAST:event_muxbuttonActionPerformed

    private void divbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divbuttonActionPerformed
        // TODO add your handling code here:
        division div=new division();
        div.show();
        dispose();
        
    }//GEN-LAST:event_divbuttonActionPerformed

    private void enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter1ActionPerformed
        // TODO add your handling code here:
        String find=search.getText();
        
        
        addition add=new addition();
        subraction sub=new subraction();
        multiplication mux=new multiplication();
        division div=new division();
        febonics feb=new febonics();
        factorial fact=new factorial();
        oddoreven OE=new oddoreven();
        palindrome pal=new palindrome();
        primenumber prime=new primenumber();
        agecalculator age=new agecalculator();
        question1 q1=new question1();
       
        
        if(find.equals("addition")){
        add.show();
        dispose();
        
        }
        else if(find.equals("subtraction")){
            sub.show();
            dispose();
            
            
        }else if(find.equals("multiplication")){
            mux.show();
            dispose();
            
        }else if(find.equals("division")){
            div.show();
            dispose();
            
        }else if(find.equals("mcq")){
            q1.show();
            dispose();
        
        
        
            
        }else if(find.equals("age calci")){
            age.show();
            dispose();
        
        
        
            
        }else if(find.equals("factorial")){
            fact.show();
            dispose();
        
        
        
            
        }else if(find.equals("odd or even")){
            OE.show();
            dispose();
        
        
        
            
        }else if(find.equals("palindrome")){
            pal.show();
            dispose();
        
        
        
            
        }else if(find.equals("primenumber")){
            prime.show();
            dispose();
        
        
        
            
        }
        
    }//GEN-LAST:event_enter1ActionPerformed

    private void xbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbutActionPerformed
        // TODO add your handling code here:
        search.setText("");
        search.requestFocus();
    }//GEN-LAST:event_xbutActionPerformed

    private void agebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agebuttonActionPerformed
        // TODO add your handling code here:
        agecalculator age=new agecalculator();
        age.show();
        dispose();
    }//GEN-LAST:event_agebuttonActionPerformed

    private void primebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primebuttonActionPerformed
        // TODO add your handling code here:
        primenumber prime=new primenumber();
        prime.show();
        dispose();
    }//GEN-LAST:event_primebuttonActionPerformed

    private void OEbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OEbuttonActionPerformed
        // TODO add your handling code here:
        oddoreven OE=new oddoreven();
        OE.show();
        dispose();
                
    }//GEN-LAST:event_OEbuttonActionPerformed

    private void BANKBUTTON4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BANKBUTTON4ActionPerformed
        // TODO add your handling code here:
        factorial fact=new factorial();
        fact.show();
        dispose();
    }//GEN-LAST:event_BANKBUTTON4ActionPerformed

    private void palindromebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palindromebuttonActionPerformed
        // TODO add your handling code here:
        palindrome pal=new palindrome();
        pal.show();
        dispose();
    }//GEN-LAST:event_palindromebuttonActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        profile p=new profile();
        p.show();
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mental".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(javaproject2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(javaproject2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(javaproject2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(javaproject2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javaproject2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BANKBUTTON4;
    private javax.swing.JButton OEbutton;
    private javax.swing.JButton addbutton;
    private javax.swing.JButton agebutton;
    private javax.swing.JButton divbutton;
    private javax.swing.JButton enter1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton muxbutton;
    private javax.swing.JButton palindromebutton;
    private javax.swing.JButton primebutton;
    private javax.swing.JTextField search;
    private javax.swing.JButton subbutton;
    private javax.swing.JButton xbut;
    // End of variables declaration//GEN-END:variables
}
